# This is the Makefile for using the Tapir toolchain to build an app.
# Include it from a bld/tapir directory in your app (built with 'maker').

include $(MAKER_ROOT)/Makefile.env

override CFLAGS += -DALPACA -DCOATI

COATI_LIB = $(COATI_ROOT)/LLVM/bld/src/libCoatiPass.so

%.coati.bc : %.bc
	$(OPT) -debug -stats -load $(COATI_LIB) \
	  -coati \
	  -o $@ $<

LINK_OBJECTS = $(OBJECTS:.o=.coati.bc)

override DEPS += libcoati

DEP_ROOT_libcoati = $(COATI_ROOT)

include $(MAKER_ROOT)/Makefile.clang
