# This is the Makefile for using the Coati toolchain to build an app.

COATIGCC_ROOT = $(LIB_ROOT)/coati

LOCAL_CFLAGS += -DALPACA \
                -DCOATI \

override DEPS += \
	libcoatigcc \

DEP_ROOT_libcoatigcc = $(COATIGCC_ROOT)
override CFLAGS += $(LOCAL_CFLAGS) \

override TOOLCHAIN = gcc
include $(MAKER_ROOT)/Makefile.gcc
