include Makefile.common

PREFIX=$(GCC_ROOT)/bin/msp430-elf-
CC=$(PREFIX)gcc
AR=$(PREFIX)ar

CFLAGS += \
	-mmcu=msp430fr5969 \
	-D__MSP430FR5969__ \
	-g \
	-O0 \
	-I$(GCC_ROOT)/include \
#	-I$(LIBIO_ROOT)/include \
	#-DMEMENTOS_FRAM \
	-I$(MEMENTOS_ROOT)/include \

.DUMMY: all
all: coatigcc.a

%.s: %.c
	$(CC) $(CFLAGS) -S -o $@ $^

#%.c: include/mementos.h

libcoatigcc.a: coatigcc.o
	$(AR) r $@ $^

clean:
	$(RM) libcoatigcc.a *.o
